# ---------------------------------------
#              dark power
# ---------------------------------------
[[plugins]]                                    
repo = 'Shougo/dein.vim' 


# ---------------------------------------
#             colorscheme ayu
# ---------------------------------------
[[plugins]] 
repo = 'ayu-theme/ayu-vim' 
name = 'ayu'


# ---------------------------------------
#           colorscheme aylin
# ---------------------------------------
# to change change specific color, you have to declare before set colorscheme
[[plugins]]
repo = 'AhmedAbdulrahman/aylin.vim'
name = 'aylin' 
hook_add = '''
'''


# ---------------------------------------
#         colorscheme  gruvbox
# ---------------------------------------
[[plugins]] 
repo = "morhetz/gruvbox"
name = "gruvbox"


# ---------------------------------------
#        NLKNguyen/papercolor-theme
# ---------------------------------------
[[plugins]] 
repo = "NLKNguyen/papercolor-theme"
name = "papercolor-theme"


# ---------------------------------------
#               indentLine
# ---------------------------------------
[[plugins]]
repo = 'Yggdroot/indentLine'


# ---------------------------------------
#             vim-js-indent
#             js ts indent
# ---------------------------------------
[[plugins]]
repo = "jason0x43/vim-js-indent"


# ---------------------------------------
#             vim-javascript
# ---------------------------------------
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx']
hook_add = """
let g:javascript_indent_disable = 1
"""

# ---------------------------------------
#             vim-styled-jsx
# ---------------------------------------
[[plugins]]
repo = 'alampros/vim-styled-jsx'
on_ft = ['javascript', 'javascript.jsx']


# -----------------------------------------
#              Git Gutters
#          < show diff + - ~ >
# -----------------------------------------
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = """
  set updatetime=100
  set signcolumn=yes
"""


# -----------------------------------------
#             openbrowser.vim
# -----------------------------------------
[[plugins]]
repo = 'tyru/open-browser.vim'


# -----------------------------------------
#          auto pairs 
# -----------------------------------------
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# -----------------------------------------
#          auto close 
# -----------------------------------------
[[plugins]]
repo = 'Townk/vim-autoclose'


# ---------------------------------------
#             comment plugin
# ---------------------------------------
# コメントが便利になる
# gccで現在の行をコメントアウト
# visualでgcで選択している行をコメントアウト
[[plugins]]
repo = "tpope/vim-commentary"


# -----------------------------------------
#           neovim terminal 強化
# -----------------------------------------
# :Tnew -> open terminal
# :T(command) -> execute command
# C-w -> exit terminal mode.
[[plugins]]
repo = 'kassio/neoterm'
hook_add = """
  let g:neoterm_default_mod='belowright'
  let g:neoterm_size=10
  let g:neoterm_autoscroll=1
  tnoremap <silent> <C-w> <C-\><C-n><C-w>
"""

# -----------------------------------------
#          自作CheatSheet plugin
# -----------------------------------------
# :Cheat -> open cheatsheet
[[plugins]]
repo = 'reireias/vim-cheatsheet'
hook_add = """
  let g:cheatsheet#cheat_file = '~/.config/nvim/cheatsheet.md'
"""

# -----------------------------------------
#          supertab (tab補完)
# -----------------------------------------
[[plugins]]
repo = 'ervandew/supertab'


# -----------------------------------------
#         vim-highlightedyank 
# -----------------------------------------
[[plugins]]
repo = 'machakann/vim-highlightedyank'
hook_add = """
let g:highlightedyank_highlight_duration = 1000
"""


# ---------------------------------------
#              vim-blade
# ---------------------------------------
[[plugins]] 
repo = "jwalton512/vim-blade"
hook_add = """
let g:blade_custom_directives = ['datetime', 'javascript']
let g:blade_custom_directives_pairs = {
      \   'markdown': 'endmarkdown',
      \   'cache': 'endcache',
      \ }
"""

# ---------------------------------------
#             alvan/vim-closetag
# ---------------------------------------
[[plugins]] 
repo = "alvan/vim-closetag"
hook_add = """
let g:closetag_filenames = '*.html,*.xhtml,*.phtml, *.php'
let g:closetag_xhtml_filenames = '*.xhtml,*.jsx'
let g:closetag_xhtml_filetypes = 'xhtml,jsx'
let g:closetag_emptyTags_caseSensitive = 1
let g:closetag_regions = {
    \ 'typescript.tsx': 'jsxRegion,tsxRegion',
    \ 'javascript.jsx': 'jsxRegion',
    \ 'typescriptreact': 'jsxRegion,tsxRegion',
    \ 'javascriptreact': 'jsxRegion',
    \ }
"""


# ---------------------------------------
#        neovim/nvim-lspconfig
# ---------------------------------------
[[plugins]] 
repo = "neovim/nvim-lspconfig"


